const works = [
  {
    id: 'top-work',
    name: 'Multi Post Stories',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work1.png',
    technology: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work2',
    name: 'Data Dashboard Healthcare',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/featured.png',
    technology: ['CSS', 'HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work3',
    name: 'Data Dashboard Healthcare',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work3.png',
    technology: ['HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work4',
    name: 'Website Portfolio',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work4.png',
    technology: ['HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work5',
    name: 'Professional Art Printing Data More',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work5.png',
    technology: ['HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work6',
    name: 'Data Dashboard Healthcare',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work6.png',
    technology: ['HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
  {
    id: 'work7',
    name: 'Website Portfolio',
    description: 'A daily selection of privately personalized reads; no accounts or sign-ups required. has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a standard dummy text.',
    image: './images/Work7.png',
    technology: ['HTML', 'Bootstrap', 'Ruby'],
    livelink: 'https://developertariq.github.io/Portfolio/',
    sourcelink: 'https://github.com/developertariq/Portfolio',
  },
];
